### ISSUE TITLE
Memory leak in Network 

### ISSUE THREAD

**Issue by wajda** [visjs/ngx-vis#211]
Apparently calling `Network.destroy()` from `ngOnDestroy()` is not enough for Vis to do a proper cleanup in Angular. It leaves a bunch of detached nodes retained by different kind of listeners.
You can see it even on the demo page - https://hypery2k.github.io/

### Steps to reproduce:
1. From the demo home page open the Network example (by clicking on the "Example" button)
1. Start memory profiling / take an initial memory snapshot in the Chrome Dev Tools
1. Click "Home" button to return on the Demo home page.
1. Click the "Example" button to re-enter the Network demo page.
1. Take another memory snapshot.
1. Repeat several times.
1. Stop memory profiling.
1. In the captured memory snapshots search for "detached" and notice growing amount of detached objects from one snapshot to another.
1. In the recorded memory timeline notice the growing JS heap, number of nodes and listeners.

<img width="1680" alt="Screenshot 2019-04-26 at 12 34 21" src="https://user-images.githubusercontent.com/795479/56802219-c763eb80-681f-11e9-96b1-ed027f521caa.png">

I have tried the simplest scenario in my blank project with only one directive that creates and destroys an empty Network object (with zero nodes in it) when the component is created and destroyed respectively. And it already leaked.

I have also tried wrapping the network creation code with the `Zone.runOutsideAngular()` hoping that it would decrease the number of retention points for vis nodes and listeners, but it didn't.

Apparently this leakage only happens when Vis is used together with Angular.

Do you have any ideas where the root cause can lie and what could be a possible workaround?

Thank you.

**Comment by hypery2k** [comment]
actually I cannot reproduce your issues.  My numbers are not increasing

**Comment by wajda** [comment]
Here is a screen recording - https://www.dropbox.com/s/mvylq3vjhvioubs/ngx-vis-211-mem-leak.mov?dl=0

**Comment by anvial** [comment]
I can use method with  takeUntil...

**Comment by hypery2k** [comment]
did you have a code snippet?

**Comment by hypery2k** [comment]
relates to #399

**Comment by hypery2k** [comment]
you give `ngx-vis@3.1.0-build1589705139` a try
