### ISSUE TITLE
Possibility to override onGroupClick event handler

### ISSUE THREAD

**Issue by tmalatinszki** [visjs/ngx-vis#246]
Hi,

I have exactly the same issue which has been already raised for vis earlier: [Nesting _onGroupClick interference with html content](https://github.com/almende/vis/issues/3333)

For short: if there is a nested group, and the user wants to create a custom group header with some additional functions the click event handler cannot catch the click itself on the custom header elements, since the default handler is registered for the whole div, and not for the small arrow icon, which manages the visibility of the child groups.

The original solution was to override the default event handler method with a custom one, but I did not find a proper way to do the same in ngx-vis yet. Would it be possible to extend the existing event handling with the nested group related ones to be able to disable the original method, and replace with a custom one based on the needs for a custom group template?

If it is not possible, is there any way to disable the original group header event handler without corrupting the original JS code?

Thanks,
Tamás

**Comment by hypery2k** [comment]
is this issue still valid?
