### ISSUE TITLE
switch to the new visjs libraries

### ISSUE THREAD

**Issue by mojoaxel** [visjs/ngx-vis#314]
Hi @hypery2k and others!

[vis.js](https://github.com/almende/vis) has been [official declared deprecated](https://github.com/almende/vis/issues/4259). We continue development in the [visjs community](https://github.com/visjs). There we have two new libraries [vis-network](https://github.com/visjs/vis-network) and [vis-timline](https://github.com/visjs/vis-timeline) and development is progressing fast.

I would highly recommend moving from the old vis dependency to the new libraries. You will find that vis-network now comes with its own typescript bindings and is moving  more and more in the direction of typescript.

Also vis-timeline has made a huge leap forward and now includes all features and bug-fixes from timeline-plus and other forks.

I also would like to invite you to collaborate with us in the new [visjs community](https://github.com/visjs). If you want you could move your fork to the visjs account. You would stay the main maintainer but we could help with reviews and maybe even share some funding :wink: 
@hypery2k Please contact me is you are interested!

**Comment by hypery2k** [comment]
Hi @mojoaxel 

I already the question to another guy from the community. I would glad to contribute it there. I'll drop you an email

**Comment by mojoaxel** [comment]
:tada: ngx-vis is now a member of the visjs family!
@hypery2k :heart: Welcome!

**Comment by mojoaxel** [comment]
One of the first thinks would be to switch to the new visjs libraries.

**Comment by hypery2k** [comment]
Just published version 3.0.0 with the new libraries: https://www.npmjs.com/package/ngx-vis?activeTab=versions

We can discuss further steps from there now ;)
