### ISSUE TITLE
Discussion: future development

### ISSUE THREAD

**Issue by mojoaxel** [visjs/ngx-vis#319]
:tada: _I'm happy that [ngx-vis](https://github.com/visjs/ngx-vis) is now part of the visjs family!_

We should discuss the future of this repository and how we could integrate it more.

Here are my first thoughts as a basis for a discussion:

1. [x] I would say one of the first steps should be to move the dependency from `vis` to [vis-timeline](https://github.com/visjs/vis-timeline) and [vis-network](https://github.com/visjs/vis-network). see #314 
2. [x] The typescript types from [vis-timeline](https://github.com/visjs/vis-timeline) and [vis-network](https://github.com/visjs/vis-network) should be used in the future. `@types/vis` is also deprecated.
3. [ ] I think the next step should be to seperate  `ngx-vis` into it's modules e.g. `@visjs/ngx-vis-timeline` and `@visjs/ngx-network`. This could e.g. be done with a monorepo approach!?
4. [x] The "donate" section of the README should be removed in favor of a opencollective badge.
5. [ ] cicle-ci? auto-release? code-formating?

**Comment by Thomaash** [comment]
Reexported stuff from Timeline and Network will have accompanying types. I don't see any problem here. The first two bullets should be fairly simple.

**Comment by hypery2k** [comment]
I've already created a branch which can be used for 1. - 3. https://github.com/visjs/ngx-vis/tree/feature/visjs-integration

Regarding 3. Yes I would go the monorepo approach. How should the npm package be named?
@visjs/ngx or @visjs/angular ?

4. Done

5. I currently use my own Jenkins server and travis. Jenkins will produce also snapshots for npm package. If we want to switch I can live with that ;)

**Comment by mojoaxel** [comment]
> Regarding 3. Yes I would go the monorepo approach. How should the npm package be named?
@visjs/ngx or @visjs/angular ?

I think the trick about the monorepo ist that the sources stay together but seperated modules can be releases out of one repository. I would recommend schema: `@visjs/ngx-vis-timeline` and `@visjs/ngx-network` ...

**Comment by hypery2k** [comment]
For the new types I've started a PR: https://github.com/visjs/ngx-vis/pull/321

Seems to require some more changes besides simple switching imports

**Comment by hypery2k** [comment]
Just published version 3.0.0 and have also [demo](https://github.com/visjs/ngx-vis/tree/develop/demo). Should we publish it also to the project homepage?

**Comment by mojoaxel** [comment]
> Should we publish it also to the project homepage?

Because it is not an independent project but "just" another way to integrate the existing libraries I would recommend to add an "Angualar-Button" to timeline and network on visjs.org.
Also It could be useful to add a sentence about this angular component to the READMEs of those libraries.

**Comment by hypery2k** [comment]
completly overlooked your last comment (@mojoaxel): So should we add it on the README ?

**Comment by hypery2k** [comment]
sounds great.  Feel free to send a PR for that

**Comment by hypery2k** [comment]
a new preview is available via `npm i ngx-vis@next`

For now, I will not have much time for further work on this, so closing this issue
