### ISSUE TITLE
minor issues in 3.0.0-alpha1

### ISSUE THREAD

**Issue by keforbes** [visjs/ngx-vis#351]
I'm sorry for being impatient but I've been itching to use this latest version.  I found a couple minor issues with the 3.0.0-alpha1 build I wanted to share.

First, the code committed in `components/network/index.ts` shows:
```
import {
  ClusterOptions,
  Data,
  DataSet,
  Edge,
  EdgeOptions,
  FitOptions,
  MoveToOptions,
  Network,
  NetworkEvents,
  Node,
  NodeOptions,
  OpenClusterOptions,
  Options,
  SelectionOptions
} from 'vis-network';
```
but the `components/network/index.ts` included in 3.0.0-alpha1 has this:
```
import { ClusterOptions, Data, DataSet, Edge, EdgeOptions, FitOptions, MoveToOptions, Network, NetworkEvents, NodeOptions, OpenClusterOptions, Options, SelectionOptions } from 'vis-network';
```
That is, it's missing `Node`.  So if you try using the network chart in 3.0.0-alpha1 you'll get an error:
```
node_modules/ngx-vis/ngx-vis"' has no exported member 'Node'.
```
I manually edited `components/network/index.ts` to match what's currently in the git repo and the issue is resolved, so this just needs another build of the 3.0.0 version.  No actual code change required here.

Second,  the only example of using this new 3.0.0 structure is in `demo/network/network-example.component.ts` but it hasn't been updated correctly.  The example shows:
```
    <div
      class="network-canvas"
      [visNetwork]="visNetwork"
      [visNetworkData]="visNetworkData"
      [visNetworkOptions]="visNetworkOptions"
      (initialized)="networkInitialized()"
    ></div>
```
but those properties have actually been renamed in the 3.0.0 branch and are now:
```
    <div 
      class="network-canvas"
      [visNetwork]="visNetwork"
      [visData]="visData"
      [visOptions]="visOptions"
      (initialized)="networkInitialized()"
    ></div>
```

I hope this helps anyone else who might be playing with this new 3.0.0-alpha1.

**Comment by hypery2k** [comment]
Resolved with publish 3.0.0
