### ISSUE TITLE
moveNode API missing

### ISSUE THREAD

**Issue by rstanziale** [visjs/ngx-vis#367]
**Is your feature request related to a problem? Please describe.**
I can't use moveNode API.

**Describe the solution you'd like**
I wrapped this need as follows:
`moveNode(visNetwork: string, idNode: string, x: number, y: number): void;`

**Comment by hypery2k** [comment]
any particular reason to no use directly [`moveNode` ](https://visjs.github.io/vis-network/docs/network/#methodManipulation)?
