### ISSUE TITLE
Error compiling with ngx-vis 3.0.1 when using a --prod build

### ISSUE THREAD

**Issue by keforbes** [visjs/ngx-vis#370]
## Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository

## Current Behavior

I bumped the version of ngx-vis from 3.0.0 to 3.0.1 and now it fails when doing a `ng build --prod`.  A normal `ng build` succeeds.

## Expected Behavior

I expect the project to compile since I didn't make any changes to my code.

## Failure Information

I tried googling the error message to see if there was something I need to change in my project to handle something differently but all the solutions seem to say the fix would be in the project throwing the error.

### Steps to Reproduce

Attempt a  `--prod` build using ngx-vis 3.0.1

### Reproduce code snippet

...

### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Angular version: 8.2.11
* NodeJS version: v13.2.0
* Operating System: Linux

### Failure Logs

```
$ ./node_modules/.bin/ng build --prod

chunk {0} runtime.1720a40670866f12654e.js (runtime) 1.45 kB [entry] [rendered]
chunk {1} main.580833eeafe7b31e9e58.js (main) 128 bytes [initial] [rendered]
chunk {2} polyfills.c3e242d22f08a71b9be2.js (polyfills) 130 bytes [initial] [rendered]
chunk {3} polyfills-es5.db559ea1da067497cb7f.js (polyfills-es5) 79.6 kB [initial] [rendered]
chunk {4} styles.abc3b66ee43159566ff8.css (styles) 599 kB [initial] [rendered]
chunk {scripts} scripts.8277eefd14e952b7d2e3.js (scripts) 638 kB [entry] [rendered]
Date: 2019-12-03T20:59:06.325Z - Hash: a4eca543f4e4f59ac0b1 - Time: 14382ms

ERROR in Unexpected value 'VisModule in ~/Documents/myapp/node_modules/ngx-vis/ngx-vis.d.ts' imported by the module 'AppModule in ~/Documents/myapp/src/app/app.module.ts'. Please add a @NgModule annotation.

$ ./node_modules/.bin/ng build

chunk {main} main.js, main.js.map (main) 197 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 309 kB [initial] [rendered]
chunk {polyfills-es5} polyfills-es5.js, polyfills-es5.js.map (polyfills-es5) 691 kB [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 6.15 kB [entry] [rendered]
chunk {scripts} scripts.js, scripts.js.map (scripts) 643 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 2.25 MB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 7.77 MB [initial] [rendered]
Date: 2019-12-03T20:59:33.094Z - Hash: f851a8a01bfd8b4f660f - Time: 15638ms

$
```

**Comment by hypery2k** [comment]
does this error stlll occur with 3.0.1?

**Comment by keforbes** [comment]
Yes, I'm still getting the error in 3.0.1.  I believe it's an issue in ng-packr.

ng-packagr/ng-packagr#892
ng-packagr/ng-packagr#355
ng-packagr/ng-packagr#594

There is a workaround to use `ng build --prod --aot=false --build-optimizer=false` but that disables optimizations so it isn't ideal.

**Comment by keforbes** [comment]
Following the example here https://github.com/ng-packagr/ng-packagr/issues/892#issue-324839596, I was able to reproduce the issue with a minimal code snippet.

First, I created a new project: `ng new test-app`
Then, I installed ngx-vis: `npm install ngx-vis`
Then, I edited `src/app/app.module.ts` to have the following contents:
```
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { VisNetworkService } from 'ngx-vis';

import { AppComponent } from './app.component';

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    VisNetworkService
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
```
(and add `allowSyntheticDefaultImports` to `tsconfig.json` to make `hammerjs` happy)

And then I just tried doing a build.  Again, succeeds with `ng build`, fails with `ng build --prod`.
```
> ng build
Generating ES5 bundles for differential loading...
ES5 bundle generation complete.

chunk {runtime} runtime-es2015.js, runtime-es2015.js.map (runtime) 6.16 kB [entry] [rendered]
chunk {runtime} runtime-es5.js, runtime-es5.js.map (runtime) 6.16 kB [entry] [rendered]
chunk {styles} styles-es2015.js, styles-es2015.js.map (styles) 10.1 kB [initial] [rendered]
chunk {styles} styles-es5.js, styles-es5.js.map (styles) 14.2 kB [initial] [rendered]
chunk {main} main-es2015.js, main-es2015.js.map (main) 46.8 kB [initial] [rendered]
chunk {main} main-es5.js, main-es5.js.map (main) 53.4 kB [initial] [rendered]
chunk {polyfills-es5} polyfills-es5.js, polyfills-es5.js.map (polyfills-es5) 790 kB [initial] [rendered]
chunk {vendor} vendor-es2015.js, vendor-es2015.js.map (vendor) 5.57 MB [initial] [rendered]
chunk {vendor} vendor-es5.js, vendor-es5.js.map (vendor) 7.95 MB [initial] [rendered]
chunk {polyfills} polyfills-es2015.js, polyfills-es2015.js.map (polyfills) 264 kB [initial] [rendered]
Date: 2019-12-11T17:31:35.312Z - Hash: dd2cb8d83fcd0bc17fc1 - Time: 33071ms
```
```
> ng build --prod

ERROR in Unexpected value 'VisNetworkService in ~/Documents/test-app/node_modules/ngx-vis/components/network/vis-network.service.d.ts' imported by the module 'AppModule in ~/Documents/test-app/src/app/app.module.ts'. Please add a @NgModule annotation.
```

**Comment by hypery2k** [comment]
you have to import the Module and not the service, see https://github.com/visjs/ngx-vis/blob/ec6fa32cf3d22be0bd68a5be47814f15410125a8/demo/demo.module.ts#L13-L23

You don't have to provide any of the service. Just import the module and DI will do all the rest

**Comment by keforbes** [comment]
That's not it.  Are you unable to reproduce this issue?

```
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { VisModule } from 'ngx-vis';

import { AppComponent } from './app.component';

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    VisModule
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

```
> ng build --prod

ERROR in Unexpected value 'VisModule in ~/Documents/test-app/node_modules/ngx-vis/ngx-vis.d.ts' imported by the module 'AppModule in ~/Documents/test-app/src/app/app.module.ts'. Please add a @NgModule annotation.
```

**Comment by sagacitysite** [comment]
I have exactly the same problem, also using ngx-vis 3.0.1 ..

`ERROR in Unexpected value 'VisModule in /home/node/app/node_modules/ngx-vis/ngx-vis.d.ts' imported by the module 'AppModule in /home/node/app/src/app/app.module.ts'. Please add a @NgModule annotation.`

**Comment by hypery2k** [comment]
no, not really. @luchsamapparat Did you have this issue also?

**Comment by luchsamapparat** [comment]
@sagacitysite did you try 3.0.*2*?

**Comment by keforbes** [comment]
3.0.2 fixed the issue for me!  Thanks!
