### ISSUE TITLE
Performance Optimization

### ISSUE THREAD

**Issue by hypery2k** [visjs/ngx-vis#388]
**Is your feature request related to a problem? Please describe.**
Vis Timeline triggers periodically via `setTimeout`  for a rerender. This causes performance issues (as shown by @luchsamapparat):

![Untitled_ Jan 22, 2020 11_25 AM](https://user-images.githubusercontent.com/979121/72886488-2cdefd00-3d0a-11ea-9b00-ff7d15bfdad4.gif)

**Describe the solution you'd like**
* We could initially run the Vis Timeline outside the ngZone, but needs then to make change detection manual
* I think we should also think about the [setTimeout](https://github.com/visjs/vis-timeline/blob/d535f69ab067fa55f06c2f2f8f95ef9019db5bb2/lib/timeline/Range.js#L152) Method

**Describe alternatives you've considered**
- 

**Additional context**
Demo: https://vistimelineexample.z22.web.core.windows.net/
Source: https://github.com/luchsamapparat/vis-timeline-example

Maybe related to #385 and #211

**Comment by hypery2k** [comment]
@Thomaash Would to show think about dropping the setTimeout here: 

https://github.com/visjs/vis-timeline/blob/2861085da96b1d76a8e31d04d87281a83979c0de/lib/timeline/Range.js#L151-L152

**Comment by Thomaash** [comment]
Timeline is best to be discussed with @yotamberk. My insight into this is limited.

**Comment by hypery2k** [comment]
Could be verified with [Lighthouse CI](https://medium.com/@leandroalmeida/performance-tests-in-your-ci-pipeline-with-lighthouse-ci-b4605009d1b2)
