### ISSUE TITLE
Unable to import VisTimeline and VisTimelineItems from 3.0.3 in Angular 9 RC 12

### ISSUE THREAD

**Issue by DelphiWorlds** [visjs/ngx-vis#394]
## Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository

## Current Behavior

VisTimeline and VisTimelineItems appear to be not exported

## Expected Behavior

VisTimeline and VisTimelineItems should be importable

## Failure Information

When writing an import statement, e.g.:

`import { VisTimeline, VisTimelineItems, VisTimelineService } from 'ngx-vis/components/timeline';`

ngx-vis/components/timeline is underlined in red, i.e. they are not exported from there. This import works:

`import { VisTimelineService } from 'ngx-vis';`

This one has VisTimeline and VisTimelineItems underlined in red:

`import { VisTimeline, VisTimelineItems, VisTimelineService } from 'ngx-vis';`

### Reproduce code snippet

[StackBlitz link](https://angular-sypgov.stackblitz.io)

**Comment by hypery2k** [comment]
Did you update from a previous ngx version? According to semver versioning version 3 was a major upgrade with breaking changes.

So these Items aren't existing anymore

**Comment by DelphiWorlds** [comment]
So what if it was a major version change? Why were they removed?

**Comment by hypery2k** [comment]
I'm sorry about that, they we're dropped in favour to using the vis.js classes directly. in previous vis.js versions (which we're not build with typescript) all typings we're built on top of the library and now with a fully ts-pure implementation it's rather easy to directly use them instead of mapping additional classes and trying to catch up the mappings with vis
If you really need these classes, feel free to open up a feature request and we'll so, who else really needs it

**Comment by alisalama** [comment]
I ran in to the same issue, and took me a while to find the right imports to update, so for anyone else... Not too much documentation on the upgrade from versions.

Change
`import { VisTimelineItems, VisTimelineItem, VisTimelineGroups, VisTimelineGroup } from 'ngx-vis';`

to

```
import { DataItem, VisTimelineService, TimelineOptions } from 'ngx-vis';
import { DataGroup } from 'vis-timeline';
```
