### ISSUE TITLE
Does not work with Angular 9?

### ISSUE THREAD

**Issue by maerni** [visjs/ngx-vis#417]
Hi

We just want to update to Angular 9 but now we have the following errors with ngx-vis 3.1.0:

`ERROR in node_modules/ngx-vis/ngx-vis.d.ts:2:22 - error NG6002: Appears in the NgModule.imports of AppModule, but could not be resolved to an NgModule class.

This likely means that the library (ngx-vis) which declares VisModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.

2 export declare class VisModule {
                       ~~~~~~~~~`

Can you please help me? Does not ngx-vis work with Angular 9?

Thanks very much.

Best regards
Mike

**Comment by maerni** [comment]
The node_modules didn't update from ngx-vis 2.x to 3.1.0

Now the errors have gone, but we wonder, if this files are not needed anymore, because they are not there anymore:

"node_modules/vis/dist/vis.min.css",
"node_modules/vis/dist/vis.min.js",

Thanks very much.

Best regards
Mike

**Comment by hypery2k** [comment]
a new preview is available via `npm i ngx-vis@next`

Otherwise track issues please here #457
