### ISSUE TITLE
Can you release 3.1.1 for the keycharm 0.3.0 legacy-peer-deps issue 

### ISSUE THREAD

**Issue by xuj4** [visjs/ngx-vis#429]
**Is your feature request related to a problem? Please describe.**
 the keycharm 0.3.0 legacy-peer-deps issue 

**Describe the solution you'd like**
release new version 3.1.1

**Describe alternatives you've considered**

**Additional context**
You fixed it last month but did not release new version. This is just a reminder since we hit the problem

**Comment by hypery2k** [comment]
sure, will release the package later today
