### ISSUE TITLE
Vis-Timeline version 7.7.0 causing 'isDataViewLike' (imported as 'isDataViewLike$1')

### ISSUE THREAD

**Issue by danielgarner64** [visjs/ngx-vis#447]
## Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository

## Current Behavior
When installing ngx-vis into a new Angular project I've tested Angular 12, 13 and 14 it will fail to work for a basic canvas with the error:

./node_modules/vis-timeline/esnext/esm/vis-timeline-graph2d.js:58:9-25 - Error: export 'isDataViewLike' (imported as 'isDataViewLike$1') was not found in 'vis-data/esnext/esm/vis-data.js' (possible exports: DELETE, DataSet, DataStream, DataView, Queue, createNewDataPipeFrom)

The issue is caused by having vis-timeline version 7.7.0 installed which is the latest version and will be installed by default because ngx-vis only locks down the major version with the requirement:
^vis-timeline: 7.3.6

The simplest fix is to lock down ngx-vis to version with the following:
~vis-timeline: 7.3.6

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Start a new project and run npm install ngx-vis
2. Create a single component that hosts a div with a [visNetwork], [visNetworkData], [visNetworkOptions], and (initalized) set.
3. Attempt to run the project.

### Reproduce code snippet

canvas.component.ts
```TS
import { Component, OnInit } from '@angular/core';
import {Data, DataSet, Edge, Node, Options, VisNetworkService} from "ngx-vis";

@Component({
  selector: 'app-canvas',
  templateUrl: './canvas.component.html',
  styleUrls: ['./canvas.component.css']
})
export class CanvasComponent implements OnInit {
  public visNetworkName: string = 'main-canvas';
  public visNetworkData: Data = { nodes: [], edges: []};
  public visNetworkOptions: Options = {};
  public nodes: DataSet<Node> = new DataSet<Node>();
  public edges: DataSet<Edge> = new DataSet<Edge>();

  public constructor(
    private visNetworkService: VisNetworkService,
  ) { }

  public ngOnInit(): void {
    this.visNetworkData = { nodes: [], edges: [] };
    this.setVisNetworkOptions();
  }

  setVisNetworkOptions(): void {
    this.visNetworkOptions = {
    };
  }

}
```

canvas.component.html
```HTML
<div
  class="custom-canvas-style"
  [visNetwork]="visNetworkName"
  [visNetworkData]="visNetworkData"
  [visNetworkOptions]="visNetworkOptions"
></div>
```

package.json
```JSON
{
  "name": "canvas-map",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "watch": "ng build --watch --configuration development",
    "test": "ng test"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^14.2.5",
    "@angular/cdk": "^14.2.4",
    "@angular/common": "^14.2.5",
    "@angular/compiler": "^14.2.5",
    "@angular/core": "^14.2.5",
    "@angular/forms": "^14.2.5",
    "@angular/material": "^14.2.4",
    "@angular/platform-browser": "^14.2.5",
    "@angular/platform-browser-dynamic": "^14.2.5",
    "@angular/router": "^14.2.5",
    "ngx-vis": "^3.1.1",
    "vis-timeline": "~7.3.6",
    "rxjs": "~7.5.0",
    "tslib": "^2.3.0",
    "zone.js": "~0.11.4"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^14.2.5",
    "@angular/cli": "^14.2.5",
    "@angular/compiler-cli": "^14.2.5",
    "@types/jasmine": "~3.10.0",
    "@types/node": "^12.11.1",
    "jasmine-core": "~4.0.0",
    "karma": "~6.3.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.1.0",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "~1.7.0",
    "typescript": "~4.6.2"
  }
}

```

### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Angular version: 12, 13, 14
* NodeJS version: 16.13.0
* Operating System: Windows

**Comment by hypery2k** [comment]
I published version 3.1.2. of the npm package...
Thx for the suggestion
