### ISSUE TITLE
Crash on layout options

### ISSUE THREAD

**Issue by moeindev** [visjs/ngx-vis#452]
## Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository

## Current Behavior

Hi the library works fine and I can show my network, but when I'm trying to add the option for hierarchical layout, I get an error that says timsort is undefined even though I already added the dependencies inside my project: 

## Expected Behavior

Should work with the options and no errors.

## Failure Information

Log: 
`core.mjs:9171 ERROR TypeError: Cannot read properties of undefined (reading 'sort')
    at LayoutEngine._getHubSizes (vis-network.js:19358:5)
    at LayoutEngine._determineLevelsByHubsize (vis-network.js:19376:25)
    at LayoutEngine.setupHierarchicalLayout (vis-network.js:18669:18)
    at Network.<anonymous> (vis-network.js:18287:12)
    at Emitter.emit (index.js:145:20)
    at Network.setData (vis-network.js:23660:21)
    at new Network (vis-network.js:23425:8)
    at VisNetworkService.create (ngxvis.js:275:37)
    at VisNetworkDirective.createNetwork (ngxvis.js:1112:32)
    at VisNetworkDirective.ngOnChanges (ngxvis.js:1086:18)`

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Add the option:
`this.visNetworkOptions = {
        layout: {
          hierarchical: {
            enabled: true,
            levelSeparation: 150,
            nodeSpacing: 100,
            treeSpacing: 200,
            blockShifting: true,
            edgeMinimization: true,
            parentCentralization: true,
            direction: 'UD', // UD, DU, LR, RL
            sortMethod: 'hubsize', // hubsize, directed
            shakeTowards: 'leaves'
          }
        }
      };`
If I set the sort method to `directed` it wont happen!
3. run the project.
4. you get it...

### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Angular version: 14.0.2
* NodeJS version: 16.17.1 npm: 6.14.13
* Operating System: Windows 10

**Comment by hypery2k** [comment]
can you retry with v4?
