### ISSUE TITLE
Can not use ngx-vis in angular 14

### ISSUE THREAD

**Issue by dsl400** [visjs/ngx-vis#453]
## Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ x] I am running the latest version
- [x ] I checked the documentation and found no answer
- [ x] I checked to make sure that this issue has not already been filed
- [ x] I'm reporting the issue to the correct repository

## Current Behavior
Can not use VisTimelineDirective in angular 14 project.

## Expected Behavior
Being able to use VisTimelineDirective in angular 14 project.

## Failure Information
When trying to import VisTimelineDirective in an standalone component in my angular 14 project I get the following error: 
Component imports must be standalone components, directives, pipes, or must be NgModules.

### Steps to Reproduce

import VisTimelineDirective in an standalone component in angular 14 

### Reproduce code snippet
@Component({
  selector: 'my-component',
  ..........
  standalone: true,
  imports: [
    VisTimelineDirective
  ]
})

...

### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Angular version: 14
* NodeJS version: 19.7
* Operating System: Linux Mint

### Failure Logs
```

```

**Comment by wlievens** [comment]
Same here! Would love to see it working, too.

**Comment by hypery2k** [comment]
a new preview is available via `npm i ngx-vis@next`

Otherwise track issues please here #457
