### ISSUE TITLE
Cannot use with Angular 16

### ISSUE THREAD

**Issue by moodyVlad** [visjs/ngx-vis#457]
## Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository

## Current Behavior
Getting the following error when importing VisModule inside another module or standalone component after update to Angular 16.
Component imports must be standalone components, directives, pipes, or must be NgModules.

## Expected Behavior

VisModule can correctly be imported when using angular 16.

## Failure Information

Component imports must be standalone components, directives, pipes, or must be NgModules.
### Steps to Reproduce
1. Create an Angular 16 application
2. Install ngx-vis
3. import VisModule inside any angular module or standalone component.

### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Angular 16.0.0:
* NodeJS version 16+:
* Operating System: W11:

**Comment by hypery2k** [comment]
Give the new version a try: `npm i ngx-vis@next`
I don't have much more capacity for the project. If any volunteer wants to take-over/step in, feel free to contact me

**Comment by Airex** [comment]
@hypery2k 
i was able to move my proj from angular 13 to 16, 

    "@angular/animations": "^16.0.2",
    "@angular/cdk": "^16.0.1",
    "@angular/common": "^16.0.2",
    "@angular/compiler": "^16.0.2",
    "@angular/core": "^16.0.2",
    "@angular/forms": "^16.0.2",
    "@angular/platform-browser": "^16.0.2",
    "@angular/platform-browser-dynamic": "^16.0.2",
    "@angular/router": "^16.0.2",
    
    "ng-zorro-antd": "^15.1.0",
    
    "ngx-vis": "3.1.2-build1683917720",
    
    "vis-data": "^7.1.6",
    "vis-util": "^5.0.3",

**Comment by Maximaximum** [comment]
`ngx-vis@next` seems to work.

@hypery2k would you please consider releasing current version as a stable release?

**Comment by hypery2k** [comment]
great to here. Will make a v4 release 

Thanks for the feedback

**Comment by hypery2k** [comment]
v4 is out out
