### ISSUE TITLE
Renovate Config

### ISSUE THREAD

**Issue by hypery2k** [visjs/ngx-vis#460]
@Thomaash I would like to enable renovate on this repo, but I don't have the rights to do so.

Could you help out here?

**Comment by Thomaash** [comment]
I don't don't have the rights either, only @mojoaxel and @yotamberk do

**Comment by mojoaxel** [comment]
@hypery2k I think/hope I did everything to enable renovate for this repo. If you have still issue please let me know!

![image](https://github.com/visjs/ngx-vis/assets/600565/d9950d20-230f-4b6b-8aa7-b325b2866681)

**Comment by hypery2k** [comment]
thx, but strange that it doesn't recognize any dependencies...

**Comment by hypery2k** [comment]
okay, it's not working because it was a fork: https://github.com/renovatebot/renovate/discussions/16172

**Comment by hypery2k** [comment]
see
```
Repository is a fork and not manually configured - skipping - did you want to run with flag --include-forks? 
```
